apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vtuber-calendar-tls
  namespace: yolo
spec:
  secretName: vtuber-calendar-tls
  dnsNames:
    - yolo.incubator4.com
    - yolo.k3s.incubator4.com
    - calendar.incubator4.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer