apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vtuber-calendar
  namespace: yolo
spec:
  entryPoints:
    - websecure
  routes:
    - match: ( Host(`calendar.incubator4.com`) || Host(`yolo.incubator4.com`) || Host(`yolo.k3s.incubator4.com`)) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: vtuber-calendar-api
          port: 8080
    - match: Host(`calendar.incubator4.com`) || Host(`yolo.incubator4.com`) || Host(`yolo.k3s.incubator4.com`)
      kind: Rule
      services:
        - name: vtuber-calendar-web
          port: 80
  tls:
    secretName: vtuber-calendar-tls