name: Deploy to Kubernetes

on:
  - workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v2.0
        with:
          version: "latest"
        id: install
      - uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy Setup Resource
        uses: Azure/k8s-deploy@v4
        with:
          namespace: "yolo"
          manifests: |
            manifests/namespace.yaml
            manifests/ingressroute.yaml
            manifests/certificate.yaml
      - name: Deploy API
        uses: Azure/k8s-deploy@v4
        with:
          namespace: "yolo"
          manifests: |
            manifests/api-deployment.yaml
            manifests/api-service.yaml
          images: "registry.cn-hangzhou.aliyuncs.com/incubator4/vtuber-calendar:api-${{ github.sha }}"
      - name: Deploy Web
        uses: Azure/k8s-deploy@v4
        with:
          namespace: "yolo"
          manifests: |
            manifests/web-deployment.yaml
            manifests/web-service.yaml
          images: "registry.cn-hangzhou.aliyuncs.com/incubator4/vtuber-calendar:web-${{ github.sha }}"

